### PR TITLE
desc for dataset

### PR DESCRIPTION
**Pull request by wey-gu**
## What type of PR is this?
- [ ] bug
- [x] feature
- [ ] enhancement

----------
- removed fifa keyword
- added desc with @slimshadylol0303 @yyh0808 's agreement, but @yyh0808 is studying on how it should be presented/designed(thanks!), after that, please @huaxiabuluo @hetao92 help with the CSS side(which I sucked🤦🏻‍♀️)

### CODE REVIEW

**Comment by wey-gu** [comment]
Need to align with @slimshadylol0303 @yyh0808 , and if this is acceptable, need to adjust the height of each card:

Screenshot 2023-02-23 at 10 01 25

**Review by slimshadylol0303 — DISMISSED** [review]

**Comment by yyh0808** [comment]
卡片高度大约增加56px，描述文字不能超过3行，标题位置固定2行高度，卡片依然保持高度一致。
截屏2023-02-23 10 41 08

**Comment by wey-gu** [comment]
thanks @yyh0808 !
@hetao92 @huaxiabuluo , the longest current description seems to fit(maximum 3 lines) already, in case not, I will try to rewrite them, could you please help co-author this PR (to help implement CSS changes on [the branch](https://github.com/vesoft-inc/nebula-studio/tree/desc_for_dataset) ) for the design? Thanks!

**Review by huaxiabuluo — APPROVED** [review]
LGTM

**Comment by wey-gu** [comment]
Screenshot 2023-02-23 at 11 39 13

Thanks

**Pull request merged**
