### PR TITLE
feat: add gpt demo

### PR DESCRIPTION
**Pull request by mizy**
## What type of PR is this?
- [ ] bug
- [ ] feature
- [ ] enhancement

#### Description:

http://192.168.8.240:7001/login

### CODE REVIEW

**Comment by wey-gu** [comment]
Great work!!!!

- Could we have a copy and run option for the chat's query block, next to the copy one?
- it seems the code block in the chat bubble is not rounded-corner, could we add a small rounded-corner to it? like what we did to the console text/code field

Screenshot 2023-07-27 at 11 58 11

- GPT seems to be a trademark, we could try rename what comes with `GPT` :-P

**Comment by wey-gu** [comment]
It seems we have LLM calling from the backend side, this means it requires the studio to be deployed with internet access, rather than all internet-calling(docs/LLM API) via the client side(browser) only, right?

**Comment by mizy** [comment]
> It seems we have LLM calling from the backend side, this means it requires the studio to be deployed with internet access, rather than all internet-calling(docs/LLM API) via the client side(browser) only, right?

yes, i use webSocket to proxy the LLM SSE response msg, and client side request sometimes may be blocked by the browser CORS

**Comment by mizy** [comment]
> Great work!!!!
> 
> * Could we have a copy and run option for the chat's query block, next to the copy one?
> * it seems the code block in the chat bubble is not rounded-corner, could we add a small rounded-corner to it? like what we did to the console text/code field
> 
> Screenshot 2023-07-27 at 11 58 11
> * GPT seems to be a trademark, we could try rename what comes with `GPT` :-P

nice suggestions, i will fix it

**Comment by wey-gu** [comment]
> > It seems we have LLM calling from the backend side, this means it requires the studio to be deployed with internet access, rather than all internet-calling(docs/LLM API) via the client side(browser) only, right?
> 
> yes, i use webSocket to proxy the LLM SSE response msg, and client side request sometimes may be blocked by the browser CORS

Aha, make sense, then this is a must :-D, we could document this requirement(that backend process of studio requires internet access.)

**Comment by mizy** [comment]
feature changed

**Pull request closed without merging**
