### PR TITLE
feat: more datasets introduced

### PR DESCRIPTION
**Pull request by wey-gu**
## What type of PR is this?
- [ ] bug
- [x] feature
- [ ] enhancement

#### Description:

- [x] SNS https://www.siwei.io/nebulagraph-sns/
- [x] data lineage https://www.siwei.io/data-lineage-oss-ref-solution/
- [x] recommendation system https://www.siwei.io/recommendation-system-with-graphdb/ https://www.siwei.io/nebulagraph-etl-dbt/
- [x] id mapping/entity resolution https://www.siwei.io/identity-resolution/
- [x] fraud detection https://www.siwei.io/fraud-detection-with-nebulagraph/
- [x] OpenStack (AI Ops) https://www.siwei.io/graph-enabled-infra-ops/
- [x] FIFA 2022 https://www.siwei.io/chatgpt-and-nebulagraph-predict-fifa-world-cup/

### CODE REVIEW

**Comment by wey-gu** [comment]
Screenshot 2023-02-21 at 22 32 33

Screenshot 2023-02-21 at 22 31 40

**Comment by huaxiabuluo** [comment]
good  job

**Comment by wey-gu** [comment]
- [x] Now the movie recommendation dataset is too big as an ngql file, I will try to do a further truncation for it and push it here, ~~please do not merge now.~~ done!

thanks!

**Review by hetao92 — APPROVED** [review]
LGTM

**Pull request merged**
