### PR TITLE
chore: update version to 3.8.0, added default /app/data dir for sqlite provisioning

### PR DESCRIPTION
**Pull request by nekomeowww**
## What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

#### Issue(s) number: 

#702 

#### Issue 1: Incompatible `ConfigMap`

Currently, it is impossible to bootstrap Nebula Studio with the Helm Chart that comes from `deployment/helm` due to the incompatible versions with `ConfigMap` resources with actual image. 

When install the Helm Chart with the following command:

```shell
helm install nebula-studio --namespace nebula . --create-namespace
```

Though all the resources can be created successfully, however, the pod will be ended at `Error` and `CrashLoopBackOff` state afterwards. When inspecting with the following commands:

```shell
$ kubectl get pods
NAME                              READY   STATUS             RESTARTS      AGE
nebula-exporter-c4bd8556b-jt2jk   1/1     Running            0             3h4m
nebula-graphd-0                   1/1     Running            0             3h4m
nebula-graphd-1                   1/1     Running            0             3h4m
nebula-metad-0                    1/1     Running            0             3h5m
nebula-metad-1                    1/1     Running            0             3h5m
nebula-metad-2                    1/1     Running            0             3h5m
nebula-storaged-0                 1/1     Running            0             3h5m
nebula-storaged-1                 1/1     Running            0             3h5m
nebula-storaged-2                 1/1     Running            0             3h5m
nebula-studio-854fd8bdc9-p6r65    0/1     CrashLoopBackOff   3 (10s ago)   70s
```

The error message states:

```shell
$ kubectl logs -f nebula-studio-854fd8bdc9-p6r65
2023/12/29 03:37:13 error: config file etc/studio-api.yaml, field File.SqliteDbFilePath is not set
```

Where `File.SqliteDbFilePath` belongs to a void line of code of nowhere, but only presents in the following code back in tag `3.7.0`:

https://github.com/vesoft-inc/nebula-studio/blob/b0e4f2474870feae96d5b8ada427afa78c22426d/server/api/studio/internal/config/config.go#L23-L28

#### Issue 2: `no such file or directory` error when using `sqlite3` as `type`

Further more, when provisioning with SQLite database as connection, server component will complain with a `no such file or directory` error since the reference to the parent directory of `./data/tasks.db` (which should be `/app/data/tasks.db` in the absolute aspect) is not exist within the container:

```shell
$ kubectl logs -f nebula-studio-74c56fbd88-wnx4b

2023/12/29 06:18:27 /server/api/studio/internal/model/db.go:78
[error] failed to initialize database, got error unable to open database file: no such file or directory
1.7038307070322847e+09	fatal	model/db.go:93	init db fail: unable to open database file: no such file or directory
github.com/vesoft-inc/nebula-studio/server/api/studio/internal/model.InitDB
	/server/api/studio/internal/model/db.go:93
github.com/vesoft-inc/nebula-studio/server/api/studio/pkg/server.InitDB
	/server/api/studio/pkg/server/server.go:21
main.main
	/server/api/studio/studio.go:53
runtime.main
	/usr/local/go/src/runtime/proc.go:267
```

#### Issue 1: Incompatible `ConfigMap`

Switch to version `3.8.0`.

#### Issue 2: `no such file or directory` error when using `sqlite3` as `type`

Provisioned a `/app/data` directory with `emptyDir` volume type to ask kubelet to ask container runtime to create a new empty directory with `/app/data` as its name when creating a new container.

## Special notes for your reviewer, ex. impact of this fix, design document, etc.

None.

### CODE REVIEW

**Comment by nekomeowww** [comment]
cc @huaxiabuluo @wey-gu PTAL

**Review by wey-gu — APPROVED** [review]

**Comment by wey-gu** [comment]
OMG, welcome to the nebulagraph community 絢香猫 老师!

THANKS! for the great contribution!!!

**Review by MegaByte875 — APPROVED** [review]
LGTM

**Review by mizy — APPROVED** [review]
good job

**Comment by QingZ11** [comment]
> The base branch restricts merging to authorized users.

🤗 Thank you for your contribution~

**Pull request merged**
