### PR TITLE
feat: optimization on colors of tags

### PR DESCRIPTION
**Pull request by wey-gu**
## What type of PR is this?
- [ ] bug
- [x] feature
- [ ] enhancement

## How do you solve it?

- jump index of the color list to make them more distinguished
- randomize starting color index (if this is not recommended, we could remove this change, let's discuss here ☺)
- hide color too close to the background
- added some colors from colorbrewer2::qualitative

### CODE REVIEW

**Review by huaxiabuluo — APPROVED** [review]
LGTM

**Comment by huaxiabuluo** [comment]
See if these colors are suitable? @yyh0808

**Comment by yyh0808** [comment]
@wey-gu 

Need to describe what colors were added, whether they are at a saturation level, and preferably post a picture to show the effect.

Also what kind of random color pickup logic is modified now.

The current color palette, in fact, only the first 7 colors, add random color logic to solve the color problem, whether only need to add random logic, without adding or removing color values

**Comment by yyh0808** [comment]
Need to consider if it overlaps with this functional requirement [issues](https://github.com/vesoft-inc/nebula-explorer-ent/issues/690)

**Comment by wey-gu** [comment]
Thanks ! @huaxiabuluo @yyh0808 

> Need to describe what colors were added, whether they are at a saturation level, and preferably post a picture to show the effect.

- They are as follow, from https://colorbrewer2.org/#type=qualitative&scheme=Set3&n=12 but with two of them removed:

Screenshot 2023-03-06 at 17 37 59

- Also some of existing were commented out due to too close the background 

Screenshot 2023-03-06 at 17 40 03

> Also what kind of random color pickup logic is modified now.

Previously it was started from index-0 and the next pick will be index + 1, but now it's index + 3

> The current color palette, in fact, only the first 7 colors, add random color logic to solve the color problem, whether only need to add random logic, without adding or removing color values

I checked with dataset(the data lineage from the starter dataset), which comes with a lot of tags, will show not only too close between tags but also, too close to the background, that's why they were proposed to be commented out.

see `match ()-[e]->() return e limit 10000` for data_lineage data set, some tags are not easy to be distinguished from the background(especially when we would like to see their prop/vid)

Screenshot 2023-03-06 at 17 46 30

**Comment by yyh0808** [comment]
I have received your feedback. The images are very clear. 

I have noticed that some of the color logic on the canvas may not have been applied to the visual results displayed in the console. 

Later, I will investigate the situation in more detail.

**Comment by hetao92** [comment]
We will provide global style modification function in subsequent versions

**Pull request closed without merging**
